data/migrations/20200318175517_users.js

Finished schema

---

api/api-routes.js
api/routes/auth/auth-route.js
api/routes/posts/posts-model.js
api/routes/posts/posts-router.js
api/routes/users/user-router.test.js
data/migrations/20200318175517_users.js

Co-authored-by: Jose N Rivera <Jrivera6869@yahoo.com>

---

README.md
api/routes/auth/auth-route.js
api/routes/auth/restricted-middleware.js
api/routes/users/user-router.test.js

added testing

---

data/db.config.js

fixed coverage

---

api/routes/auth/auth-route.js
api/routes/auth/middleware.js
api/routes/posts/posts-router.js
api/routes/users/user-route.js
data/migrations/20200318175517_users.js
data/migrations/20200320133723_platforms.js
data/seeds/001_users.js
package-lock.json
package.json

Jose rivera

---

api/routes/auth/auth-route.js
api/routes/auth/middleware.js
api/routes/posts/posts-router.js
api/routes/users/user-route.js

Scheduled post feature

---

api/routes/auth/model-helper.test.js

Added more dynamic tests

---

knexfile.js

Modify knexfile for local development

update knexfile for local pg

---

api/helper.js
api/routes/auth/middleware.js
api/routes/posts/posts-router.js
api/routes/topics/topics-router.js
api/routes/users/user-route.js

Should not conflict with DB config and migration update.

Removed Joi, updated helper.js importing.

---

package.json

Removes prescript to fix Heroku deployment failure

Remove prescript script

---

package.json

update server:c9 script

---

api/middleware/verifyJWT.js
api/middleware/verifyUser.js
api/models/usersModel.js
api/routers/apiRouter.js
api/routers/userRouter.js
knexfile.js

Persist user to postgres from okta after login

persist user to postgres from okta after login

---

api/middleware/verifyJWT.js
api/middleware/verifyUser.js
api/routers/auth/authRouter.js
api/routers/userRouter.js

Use signed claims from JWT to update user in postgres

Use signed claims from JWT to update user in postgres

---

api/middleware/matchUser.js
api/models/listModel.js
api/models/postsModel.js
api/routers/userRouter.js

Added GET and POST endpoints for /users/lists and /users/posts; coded (but did not activate) middleware to match logged-in user to resource owner.

Auth users endpoints

---

api/middleware/verifyJWT.js
api/middleware/verifyUserId.js
api/routers/listRouter.js
api/routers/postRouter.js
api/routers/userRouter.js

Bug fix/routes

---

api/models/usersModel.js
api/routers/userRouter.js

Fix data persistence issues on back-end

Fix data persistence issues on back-end

---

api/middleware/verifyJWT.js
api/middleware/verifyTwitter.js
api/models/postsModel.js
api/routers/postRouter.js

Co-authored-by: M Groesbeck <m.groesbeck@gmail.com>
Co-authored-by: Tim Shaker <tim@tmshkr.com>
Co-authored-by: Jack Kim <jackskim29@gmail.com>
Co-authored-by: Eddie Madrigal <edmadrigal@yahoo.com>
Co-authored-by: Fabricio Bezerra <fabricio.spb@gmail.com>
Co-authored-by: Aja Blanco <ajakblanco@gmail.com>
Initial set-up for post now to twitter feature
- [] Complete, tested, ready to review and merge

set up twitter post now PR

---

api/models/listModel.js
api/models/postsModel.js

fix update method in listModel to return the object instead of an array

---

api/routers/__tests__/postRouter.test.js
api/routers/postRouter.js

PUT /api/posts/:id/schedule endpoint and tests, allowing the user to schedule a post to be Tweeted at a future date

Post scheduling API endpoint and tests

---

api/routers/postRouter.js

save post id to node-scheduler schedule to change schedule

---

.prettierrc
api/routers/postRouter.js

verify if post still exists before post it in the scheduler function
